# Generated by Django 4.2.5 on 2023-10-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_book_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='請輸入書本所擁有的語言', max_length=50),
        ),
    ]
