# Generated by Django 4.2.5 on 2023-10-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_died',
            field=models.DateField(blank=True, null=True, verbose_name='死亡日期'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='姓氏'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='小於13字 <a href="https://www.isbn-international.org/content/what-isbn"> ISBN號碼</a>', max_length=13, verbose_name='ISBN編號'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='請輸入書本簡介', max_length=1000, verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='書名'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='輸入你的書籍類別 Ex: 科學、生物、資訊', max_length=200, verbose_name='書本類型'),
        ),
    ]
