# Generated by Django 4.2.5 on 2023-10-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_book_author_alter_bookinstance_due_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', '保養中'), ('o', '已被租借'), ('a', '可租借'), ('r', '已預定')], default='m', help_text='預定中', max_length=1, verbose_name='書本狀態'),
        ),
    ]
