# Generated by Django 4.2.5 on 2023-10-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_bookinstance_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_died',
            new_name='date_of_death',
        ),
    ]
