# Generated by Django 4.2.5 on 2023-10-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', '可以看到所有以租借的書本'),)},
        ),
    ]
